apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/managed-by: synapse

resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml

namespace: test